{% set name = "compas_view2" %}
{% set version = "0.1.0" %}
{% set hash = "c9a816ed3c5a903d62e6cab8d94d934329d536db4409fc1b549de43d25adf5c9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/compas-dev/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1
  skip: true  # [py<36 or py>38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - cython
    - compas
    - python.app  # [osx]
    - freeglut  # [win]

test:
  imports:
    - compas_view2

about:
  home: https://github.com/compas-dev/compas_view2
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: 'COMPAS friendly wrappers for CGAL algorithms.'
  dev_url: https://github.com/compas-dev/compas_cgal
  doc_url: https://github.com/compas-dev/compas_cgal

extra:
  recipe-maintainers:
    - brgcode
    - gonzalocasas
